"""change starttime data type to datetime

Revision ID: 0dc2d79a9014
Revises: e21bd4710a94
Create Date: 2020-08-21 00:51:50.361442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dc2d79a9014'
down_revision = 'e21bd4710a94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('start_time', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
