"""add venue description nullable

Revision ID: 546c172a12f9
Revises: a6531d488956
Create Date: 2020-08-23 18:32:10.225813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '546c172a12f9'
down_revision = 'a6531d488956'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artist', 'seeking_venue',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artist', 'seeking_venue',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
