"""change starttime data type to datetime

Revision ID: 77f0f0d19d09
Revises: 0dc2d79a9014
Create Date: 2020-08-21 00:52:07.204650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77f0f0d19d09'
down_revision = '0dc2d79a9014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('start_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'start_time')
    # ### end Alembic commands ###
