"""add coloum

Revision ID: a98064934e35
Revises: 42843bb02f5f
Create Date: 2020-08-20 01:24:08.187426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a98064934e35'
down_revision = '42843bb02f5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_venue', sa.Boolean(), nullable=False))
    op.add_column('venue', sa.Column('seeking_description', sa.String(length=500), nullable=False))
    op.add_column('venue', sa.Column('seeking_talent', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'seeking_talent')
    op.drop_column('venue', 'seeking_description')
    op.drop_column('artist', 'seeking_venue')
    # ### end Alembic commands ###
