"""change show_time to start_time

Revision ID: e21bd4710a94
Revises: eb9b9c8ce62f
Create Date: 2020-08-21 00:39:31.011494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e21bd4710a94'
down_revision = 'eb9b9c8ce62f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('start_time', sa.Integer(), nullable=False))
    op.drop_column('show', 'show_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('show_time', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('show', 'start_time')
    # ### end Alembic commands ###
